version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - REPOSITORY_URI__SERVICE_DISCOVERY=790161600376.dkr.ecr.us-east-1.amazonaws.com/service-discovery
      - REPOSITORY_URI__USERS=790161600376.dkr.ecr.us-east-1.amazonaws.com/users
      - REPOSITORY_URI__ARTICLES=790161600376.dkr.ecr.us-east-1.amazonaws.com/articles
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI__SERVICE_DISCOVERY:latest ./service-discovery --target prod
      - docker build -t $REPOSITORY_URI__USERS:latest ./users --target prod
      - docker build -t $REPOSITORY_URI__ARTICLES:latest ./articles --target prod
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI__SERVICE_DISCOVERY:latest
      - docker push $REPOSITORY_URI__USERS:latest
      - docker push $REPOSITORY_URI__ARTICLES:latest
